# Generated by Django 2.1.7 on 2019-03-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprazamentos', '0003_auto_20190312_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprazamento',
            old_name='aplicação',
            new_name='aplicacao',
        ),
    ]
