# Generated by Django 2.1.7 on 2019-03-13 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aprazamentos', '0004_auto_20190312_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprazamento',
            name='horario',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
