# Generated by Django 2.1.7 on 2019-03-30 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprazamentos', '0006_aprazamento_medicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprazamento',
            name='medicamento',
        ),
    ]
