# Generated by Django 2.1.7 on 2019-04-01 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0005_remove_medicamento_aprazamento'),
        ('aprazamentos', '0007_remove_aprazamento_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprazamento',
            name='medicamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Medicamento'),
            preserve_default=False,
        ),
    ]
