# Generated by Django 2.1.7 on 2019-04-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprazamentos', '0011_auto_20190401_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprazamento',
            options={},
        ),
    ]
