# Generated by Django 2.1.7 on 2019-04-20 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aprazamentos', '0012_auto_20190401_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprazamento',
            name='aplicacao',
        ),
        migrations.RemoveField(
            model_name='aprazamento',
            name='horario',
        ),
        migrations.AddField(
            model_name='aprazamento',
            name='data_aplicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprazamento',
            name='data_programada',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aprazamento',
            name='hora_aplicacao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprazamento',
            name='hora_programada',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
