# Generated by Django 2.1.7 on 2019-07-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprazamentos', '0013_auto_20190420_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprazamento',
            name='erro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
