# Generated by Django 2.1.7 on 2019-07-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprazamentos', '0014_aprazamento_erro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprazamento',
            name='erro',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
