# Generated by Django 2.1.7 on 2019-03-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
