# Generated by Django 2.1.7 on 2019-03-20 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='aprazamento',
        ),
    ]
