# Generated by Django 2.1.7 on 2019-03-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aprazamentos', '0007_remove_aprazamento_medicamento'),
        ('medicamentos', '0002_remove_medicamento_aprazamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='aprazamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aprazamentos.Aprazamento'),
            preserve_default=False,
        ),
    ]
