# Generated by Django 2.1.7 on 2019-04-01 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0017_remove_prescricao_medicamentos'),
        ('medicamentos', '0003_medicamento_aprazamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='prescricao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prescricoes.Prescricao'),
            preserve_default=False,
        ),
    ]
