# Generated by Django 2.1.7 on 2019-04-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0004_medicamento_prescricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='aprazamento',
        ),
    ]
