# Generated by Django 2.1.7 on 2019-04-01 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0005_remove_medicamento_aprazamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='prescricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='prescricoes.Prescricao'),
        ),
    ]
