# Generated by Django 2.1.7 on 2019-04-01 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0006_auto_20190401_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='descricao',
            new_name='medicamento',
        ),
    ]
