# Generated by Django 2.1.7 on 2019-04-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0008_medicamento_anotacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='prescricao',
        ),
    ]
