# Generated by Django 2.1.7 on 2019-04-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0022_auto_20190402_2245'),
        ('medicamentos', '0009_remove_medicamento_prescricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='prescricao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='prescricoes.Prescricao'),
            preserve_default=False,
        ),
    ]
