# Generated by Django 2.1.7 on 2019-02-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('leito', models.IntegerField()),
                ('prontuario', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
    ]
