# Generated by Django 2.1.7 on 2019-03-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='leito',
        ),
    ]
