# Generated by Django 2.1.7 on 2019-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_remove_paciente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
