# Generated by Django 2.1.7 on 2019-03-28 02:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(max_length=14, unique=True, verbose_name='Usuário')),
                ('is_medico', models.BooleanField(default=False, verbose_name='Médico')),
                ('is_enfermagem', models.BooleanField(default=False, verbose_name='Enfermagem')),
                ('is_farmacia', models.BooleanField(default=False, verbose_name='Fármacia')),
                ('is_paciente', models.BooleanField(default=False, verbose_name='Paciente')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='Equipe')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
