# Generated by Django 2.1.7 on 2019-03-28 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'secretary'), (4, 'supervisor'), (5, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_enfermagem',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_farmacia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_medico',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_paciente',
        ),
        migrations.AddField(
            model_name='user',
            name='credencial',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número do Conselho'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nome de Usuário'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Role'),
            preserve_default=False,
        ),
    ]
