# Generated by Django 2.1.7 on 2019-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190328_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'dsaasd'), (2, 'asdasd'), (3, 'dasdasd'), (4, 'dsasdas'), (5, 'dsadasd')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[(1, 'dsaasd'), (2, 'asdasd'), (3, 'dasdasd'), (4, 'dsasdas'), (5, 'dsadasd')], default=1, max_length=9),
        ),
    ]
