# Generated by Django 2.1.7 on 2019-05-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190329_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome da mãe'),
        ),
    ]
