# Generated by Django 2.1.7 on 2019-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0002_auto_20190218_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='prescricoes'),
        ),
    ]
