# Generated by Django 2.1.7 on 2019-02-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0003_prescricao_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
