# Generated by Django 2.1.7 on 2019-02-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0004_prescricao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='data',
            field=models.DateField(),
        ),
    ]
