# Generated by Django 2.1.7 on 2019-02-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0005_auto_20190218_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='dosagem',
        ),
        migrations.RemoveField(
            model_name='prescricao',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='prescricao',
            name='via',
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='medicamento',
            field=models.TextField(max_length=150),
        ),
    ]
