# Generated by Django 2.1.7 on 2019-02-18 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0007_auto_20190218_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescricao',
            old_name='medicamento',
            new_name='prescricao',
        ),
    ]
