# Generated by Django 2.1.7 on 2019-02-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0008_auto_20190218_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='prescricao',
            field=models.CharField(max_length=100),
        ),
    ]
