# Generated by Django 2.1.7 on 2019-02-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0009_auto_20190218_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='prescricao',
            field=models.TextField(max_length=100),
        ),
    ]
