# Generated by Django 2.1.7 on 2019-02-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0010_auto_20190218_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='prescricao',
            field=models.TextField(),
        ),
    ]
