# Generated by Django 2.1.7 on 2019-04-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0016_auto_20190401_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='medicamentos',
        ),
    ]
