# Generated by Django 2.1.7 on 2019-04-01 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0017_remove_prescricao_medicamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='prescricao',
            name='prescricao',
        ),
        migrations.AddField(
            model_name='prescricao',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
