# Generated by Django 2.1.7 on 2019-04-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0018_auto_20190401_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='anotacoes',
        ),
    ]
