# Generated by Django 2.1.7 on 2019-04-03 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0019_remove_prescricao_anotacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente'),
        ),
    ]
