# Generated by Django 2.1.7 on 2019-04-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0020_auto_20190402_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente'),
        ),
    ]
