# Generated by Django 2.1.7 on 2019-04-03 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0021_auto_20190402_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
