# Generated by Django 2.1.7 on 2019-10-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0023_prescricao_leito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
